name: update-flake-lock-zellij
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * *' # runs daily at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    environment: update
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock zellij input
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          inputs: zellij
          pr-labels: |
            dependencies
            automated
            nix
      - name: setup git
        run: |
          set -xe
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          nix build .#zellij.src.outPath
          cp -Rp ./result ./vendor
          run chmod a+w ./vendor/Cargo.lock
          cd $GITHUB_REPOSITORY/vendor
          nix develop --command cargo update
          git add $GITHUB_REPOSITORY/vendor/Cargo.lock
          git commit -m "$(date)"
        shell: bash

